### ISSUE TITLE
Spaces in vernacular solr field names

### ISSUE THREAD

**Issue by corylown** [trln/argot-ruby#15] opened 2017-02-23 19:05 UTC
After running the ingest process ```argot ingest ../unc.json -s http://127.0.0.1:8983/solr/trln``` my solr index has a few field names that have spaces in them. A bug?

```
authors_main_ u _v_a
authors_main_ u _v_t
imprint_ u _v_a
imprint_ u _v_t
statement_of_responsibility_ u _v_a
statement_of_responsibility_ u _v_t
```

**Comment by queryluke** [comment] 2017-02-23 19:11
the suffixer appends *_v_t to any vernacular fields, where * is the 3 letter language code.

definitely a bug, but the cause is that in the marc-to-argot translation, " u " is getting marked as the lang_code.

Either way, it's something I need to work through.

**Closed** 2017-02-27 19:01 UTC
Labels: bug
